### ISSUE TITLE
Math symbols are not converted

### ISSUE THREAD

**Issue by ahenkes1** [GjjvdBurg/paper2remarkable#109]
Using the standard settings of `p2r`, math symbols are not displayed correctly, e.g.

`p2r  -n http://alexkritchevsky.com/2020/10/15/ea-operations.html `

leads to 

![Screenshot from 2021-05-23 12-16-07](https://user-images.githubusercontent.com/62153181/119256386-c9e0cd00-bbc0-11eb-8e70-8ef65701500e.png)

What am I missing?

**Comment by GjjvdBurg** [comment]
Hi @ahenkes1,

Math symbols are typically rendered using Javascript after the page loads. With `p2r` the raw html is downloaded, and readability/readabilipy is used to extract the "main" content. There is no support for running the Javascript that is called on page load, since `p2r` isn't emulating a browser fully.

The best solution is probably to use the browser to print the file to PDF, and then send that to the reMarkable using `p2r`. If you're on Mac, I think you can do this in one go using the [Printing to p2r](https://github.com/GjjvdBurg/paper2remarkable#printing) guide.

Hope this helps!

**Comment by ahenkes1** [comment]
Thank you very much for your help, @GjjvdBurg !
