### ISSUE TITLE
Installation Struggles on MacOS

### ISSUE THREAD

**Issue by la32094uf** [GjjvdBurg/paper2remarkable#137]
Had issues on installing on a MacOS M1 / Ventura

because:
### Installing Rmapi
`go get -u github.com/juruen/rmapi ` --> had to install go --> newest version of go does not support `get -u` anymore. 

Tried to install it via 
```
git clone https://github.com/juruen/rmapi 
cd rmapi
go install
```
But then p2r could not find the binary.

So instead I downloaded the rmapi binary, and placed this in /usr/local/bin (Don't think it is the best way to go).

### Installing dependencies
this worked

### installing paper2remarkable
`pip` did not work, so I had to install it. But then only pip3 was possible to launch.
So I had to do 
`pip3 install paper2remarkable`

### running paper2remarkable
Then I ran into a problem that weasyprint _cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002):_ 
Because the symlinks are not working?!
Fixed this with:
`sudo ln -s /opt/homebrew/lib /usr/local/lib` (Don't think it is the best way to go).

But then when running p2r from the terminal it says:
`zsh: command not found: p2r`

Did a system-search, and found p2r at: `/Users/XXXX/Library/Python/3.9/bin/p2r`

Then I ran the command: 
`/Users/XXXXX/Library/Python/3.9/bin/p2r https://arxiv.org/abs/1811.11242`

and it finally worked.....

**Comment by GjjvdBurg** [comment]
Hi @la32094uf, thanks for documenting these issues. As far as I can tell they are more related to installation directories and the PATH variable configuration on your system than actual problems that we can fix in p2r. Instructions to install `rmapi` have since been updated in the readme. Hopefully your solutions will help anyone with similar issues in the future.
