### ISSUE TITLE
Multiple definitions in dictionary at byte 0xbe2 for key /ToUnicode

### ISSUE THREAD

**Issue by sirupsen** [GjjvdBurg/paper2remarkable#51]
```
p2r --right https://www.manuelrigger.at/preprints/NoREC.pdf
```

You seen this before?

**Comment by GjjvdBurg** [comment]
Hi @sirupsen, thanks for reporting this! I havn't encountered this problem before, but it appears to be due to some encoding problem in the PDF file. Passing it through GhostScript before any of the other
operations seems to solve it, and that step doesn't affect the output otherwise so it's an acceptable solution.
