### ISSUE TITLE
Feature to split two column pdfs into one column per page

### ISSUE THREAD

**Issue by karanprime** [GjjvdBurg/paper2remarkable#61]
Since many academic papers are in two column format, splitting them into one column per page might be useful for readability and notetaking on the 10.3" display. The two columns are usually symmetrical. So, this could be done by cropping the two vertical halves of a pdf page.

#### Input:
<img width="716" alt="Screen Shot 2020-10-05 at 8 38 56 AM" src="https://user-images.githubusercontent.com/7028593/95038249-49319700-06eb-11eb-8786-37149da0b058.png">

#### Split areas:
<img width="715" alt="Screen Shot 2020-10-05 at 8 40 35 AM" src="https://user-images.githubusercontent.com/7028593/95038265-577fb300-06eb-11eb-9148-5595c6f4e0f6.png">

#### Output:
<img width="785" alt="Screen Shot 2020-10-05 at 9 16 32 AM" src="https://user-images.githubusercontent.com/7028593/95038376-9150b980-06eb-11eb-9e9c-2a3ae493b319.png">
<img width="781" alt="Screen Shot 2020-10-05 at 9 16 44 AM" src="https://user-images.githubusercontent.com/7028593/95038388-96156d80-06eb-11eb-85dd-a188d332bb52.png">
PDF: 
[split_2col.pdf](https://github.com/GjjvdBurg/paper2remarkable/files/5325109/split_2col.pdf)

### Nice to have
A command line flag to exclude the first page (with title and abstract) from splitting.
<img width="717" alt="Screen Shot 2020-10-05 at 8 39 16 AM" src="https://user-images.githubusercontent.com/7028593/95038512-ee4c6f80-06eb-11eb-84ae-d5a526bdb49f.png">

**Comment by GjjvdBurg** [comment]
Hi @karanprime,

Thanks for the suggestion! This sounds like an interesting idea, but I don't know how easy it would be to implement. I'm not aware of any libraries that allow you to detect the columns accurately, so that would be a non-trivial exercise. Perhaps a useful work-around would be to use [arxiv-vanity](https://www.arxiv-vanity.com/) instead, and use ``paper2remarkable`` on that (this works for arXiv papers where the LaTeX source is available). I admit this isn't a perfect solution, as it doesn't seem to preserve math very well.

Of course, if you'd like to implement this yourself I'd be happy to consider the pull request!

**Comment by karanprime** [comment]
Arxiv-vanity is a great idea! I will try using that, might even work with the chrome extension. 

I would be happy to give it a shot. I don't know how to manipulate pdfs with python but I will follow [crop.py](https://github.com/GjjvdBurg/paper2remarkable/blob/master/paper2remarkable/crop.py).

**Comment by GjjvdBurg** [comment]
The tricky bit will be finding the bounding boxes of the columns, once you have that you can indeed use the code in ``crop.py`` to extract that part of the page. Detecting these bounding boxes is not trivial, but there is [research on this problem](https://github.com/ibm-aur-nlp/PubLayNet). That repo also highlights that you'd have to figure out how to deal with images and tables the span multiple columns.

**Comment by GjjvdBurg** [comment]
I'm closing this for now as I don't currently have plans to implement this myself, but of course you're still welcome to submit a pull request if you've found a solution.
